ingredients = [
  # Vodka
  "Vodka",
  "Vanilla Vodka",
  "Citrus Vodka",
  "Pepper Vodka",
  "Espresso Vodka",

  # Gin
  "London Dry Gin",
  "Old Tom Gin",
  "Plymouth Gin",
  "Navy Strength Gin",
  "Genever",

  # Rum
  "White Rum",
  "Gold Rum",
  "Dark Rum",
  "Black Rum",
  "Aged Rum",
  "Spiced Rum",
  "Overproof Rum",
  "Coconut Rum",
  "Demerara Rum",
  "Rhum Agricole",
  "Cachaça",

  # Tequila and agave
  "Blanco Tequila",
  "Reposado Tequila",
  "Añejo Tequila",
  "Extra Añejo Tequila",
  "Cristalino Tequila",
  "Mezcal",
  "Raicilla",
  "Sotol",

  # Whiskey
  "Bourbon",
  "Rye Whiskey",
  "Tennessee Whiskey",
  "Irish Whiskey",
  "Scotch Whisky",
  "Blended Scotch",
  "Single Malt Scotch",
  "Canadian Whisky",
  "Japanese Whisky",
  "Corn Whiskey",

  # Brandy
  "Brandy",
  "Cognac",
  "Armagnac",
  "Apple Brandy",
  "Calvados",
  "Pear Brandy",
  "Pisco",
  "Grappa",
  "Kirsch",

  # Fortified wines and aperitifs
  "Sweet Vermouth",
  "Dry Vermouth",
  "Bianco Vermouth",
  "Rosé Vermouth",
  "Lillet Blanc",
  "Lillet Rosé",
  "Cocchi Americano",
  "Dubonnet Rouge",
  "Sherry",
  "Fino Sherry",
  "Amontillado Sherry",
  "Oloroso Sherry",
  "Pedro Ximénez Sherry",
  "Port Wine",
  "Madeira",
  "Marsala",

  # Bitter aperitifs and amari
  "Campari",
  "Aperol",
  "Cynar",
  "Fernet-Branca",
  "Averna",
  "Amaro Montenegro",
  "Amaro Nonino",
  "Ramazzotti",
  "Cardamaro",
  "Select Aperitivo",
  "Suze",
  "Salers",
  "Bonal",

  # Orange and citrus liqueurs
  "Triple Sec",
  "Cointreau",
  "Grand Marnier",
  "Orange Curaçao",
  "Blue Curaçao",
  "Dry Curaçao",
  "Limoncello",
  "Yuzu Liqueur",

  # Fruit liqueurs
  "Peach Schnapps",
  "Apricot Brandy Liqueur",
  "Cherry Liqueur",
  "Maraschino Liqueur",
  "Black Raspberry Liqueur",
  "Crème de Cassis",
  "Crème de Mûre",
  "Strawberry Liqueur",
  "Banana Liqueur",
  "Melon Liqueur",
  "Watermelon Liqueur",
  "Passion Fruit Liqueur",
  "Lychee Liqueur",
  "Mango Liqueur",
  "Pear Liqueur",
  "Apple Liqueur",
  "Pomegranate Liqueur",
  "Elderflower Liqueur",
  "Fig Liqueur",

  # Nut, coffee and dessert liqueurs
  "Amaretto",
  "Frangelico",
  "Hazelnut Liqueur",
  "Walnut Liqueur",
  "Coffee Liqueur",
  "Chocolate Liqueur",
  "White Chocolate Liqueur",
  "Crème de Cacao",
  "Irish Cream",
  "Licor 43",
  "Drambuie",
  "Bénédictine",
  "Galliano",
  "Anise Liqueur",
  "Absinthe",
  "Sambuca",
  "Ouzo",
  "Pastis",

  # Floral and herbal liqueurs
  "Chartreuse",
  "Green Chartreuse",
  "Yellow Chartreuse",
  "Crème de Violette",
  "Rose Liqueur",
  "Lavender Liqueur",
  "Ginger Liqueur",
  "Allspice Dram",
  "Falernum",

  # Beer, wine and sparkling wine
  "Champagne",
  "Prosecco",
  "Cava",
  "Sparkling Wine",
  "Red Wine",
  "White Wine",
  "Rosé Wine",
  "Stout",
  "Lager",
  "IPA",
  "Wheat Beer",
  "Ginger Beer",
  "Hard Cider",
  "Sake",
  "Soju",
  "Makgeolli",

  # Bitters
  "Angostura Bitters",
  "Orange Bitters",
  "Peychaud's Bitters",
  "Chocolate Bitters",
  "Coffee Bitters",
  "Grapefruit Bitters",
  "Lavender Bitters",
  "Cardamom Bitters",
  "Celery Bitters",
  "Mole Bitters",
  "Walnut Bitters",
  "Cherry Bitters",
  "Aromatic Bitters",

  # Citrus juice
  "Lemon Juice",
  "Lime Juice",
  "Orange Juice",
  "Grapefruit Juice",
  "Yuzu Juice",
  "Tangerine Juice",
  "Mandarin Juice",
  "Blood Orange Juice",
  "Key Lime Juice",

  # Fruit juice
  "Pineapple Juice",
  "Cranberry Juice",
  "Apple Juice",
  "Pear Juice",
  "Pomegranate Juice",
  "Tomato Juice",
  "Watermelon Juice",
  "Mango Juice",
  "Passion Fruit Juice",
  "Guava Juice",
  "Peach Juice",
  "Cherry Juice",
  "Lychee Juice",
  "Coconut Water",

  # Fresh fruit
  "Lemon",
  "Lime",
  "Orange",
  "Grapefruit",
  "Blood Orange",
  "Pineapple",
  "Strawberry",
  "Raspberry",
  "Blackberry",
  "Blueberry",
  "Cherry",
  "Peach",
  "Pear",
  "Apple",
  "Watermelon",
  "Mango",
  "Passion Fruit",
  "Pomegranate",
  "Fig",
  "Lychee",
  "Cucumber",
  "Jalapeño",
  "Serrano Pepper",
  "Habanero Pepper",

  # Syrups and sweeteners
  "Simple Syrup",
  "Rich Simple Syrup",
  "Demerara Syrup",
  "Brown Sugar Syrup",
  "Honey Syrup",
  "Agave Syrup",
  "Maple Syrup",
  "Grenadine",
  "Orgeat",
  "Vanilla Syrup",
  "Cinnamon Syrup",
  "Ginger Syrup",
  "Passion Fruit Syrup",
  "Raspberry Syrup",
  "Strawberry Syrup",
  "Peach Syrup",
  "Pineapple Syrup",
  "Coconut Syrup",
  "Caramel Syrup",
  "Chocolate Syrup",
  "Lavender Syrup",
  "Rose Syrup",
  "Hibiscus Syrup",
  "Mint Syrup",
  "Gum Syrup",
  "Cola Syrup",

  # Carbonated mixers
  "Club Soda",
  "Tonic Water",
  "Ginger Ale",
  "Cola",
  "Lemon-Lime Soda",
  "Grapefruit Soda",
  "Sparkling Water",
  "Mineral Water",
  "Root Beer",
  "Cream Soda",

  # Non-carbonated mixers
  "Sweet and Sour Mix",
  "Bloody Mary Mix",
  "Margarita Mix",
  "Lemonade",
  "Limeade",
  "Iced Tea",
  "Black Tea",
  "Green Tea",
  "Chai Tea",
  "Coffee",
  "Cold Brew Coffee",
  "Espresso",
  "Hot Chocolate",

  # Dairy and creamy ingredients
  "Heavy Cream",
  "Half-and-Half",
  "Whole Milk",
  "Oat Milk",
  "Almond Milk",
  "Coconut Milk",
  "Coconut Cream",
  "Cream of Coconut",
  "Condensed Milk",
  "Evaporated Milk",
  "Vanilla Ice Cream",

  # Egg and foaming ingredients
  "Egg White",
  "Whole Egg",
  "Aquafaba",
  "Cocktail Foamer",

  # Herbs
  "Mint",
  "Basil",
  "Thai Basil",
  "Rosemary",
  "Thyme",
  "Sage",
  "Cilantro",
  "Tarragon",
  "Shiso",
  "Lemongrass",

  # Spices
  "Cinnamon",
  "Nutmeg",
  "Clove",
  "Cardamom",
  "Star Anise",
  "Allspice",
  "Black Pepper",
  "Pink Peppercorn",
  "Cayenne Pepper",
  "Chili Powder",
  "Smoked Paprika",
  "Ginger",
  "Turmeric",
  "Vanilla Bean",

  # Salts, sugars and rims
  "Kosher Salt",
  "Sea Salt",
  "Flaky Salt",
  "Smoked Salt",
  "Celery Salt",
  "Tajín",
  "Granulated Sugar",
  "Brown Sugar",
  "Demerara Sugar",
  "Powdered Sugar",
  "Cinnamon Sugar",

  # Savory ingredients
  "Worcestershire Sauce",
  "Hot Sauce",
  "Tabasco",
  "Soy Sauce",
  "Fish Sauce",
  "Olive Brine",
  "Pickle Brine",
  "Gochujang",
  "Wasabi",
  "Horseradish",
  "Balsamic Vinegar",
  "Apple Cider Vinegar",
  "Rice Vinegar",

  # Garnishes
  "Lemon Peel",
  "Lime Peel",
  "Orange Peel",
  "Grapefruit Peel",
  "Cocktail Cherry",
  "Maraschino Cherry",
  "Luxardo Cherry",
  "Olive",
  "Cocktail Onion",
  "Cucumber Slice",
  "Pineapple Wedge",
  "Mint Sprig",
  "Rosemary Sprig",
  "Cinnamon Stick",
  "Star Anise Pod",
  "Edible Flower",
  "Dehydrated Citrus Wheel",

  # Specialty ingredients
  "Activated Charcoal",
  "Butterfly Pea Tea",
  "Hibiscus Tea",
  "Matcha",
  "Ube",
  "Tamarind",
  "Black Sesame",
  "Sesame Oil",
  "Peanut Butter",
  "Almond Butter",
  "Miso",
  "Seaweed",
  "Salted Caramel",
  "Chocolate",
  "Cocoa Powder",
  "Espresso Powder"
]

ingredients.each do |name|
  Ingredient.find_or_create_by!(name: name)
end

puts "Seeded #{Ingredient.count} ingredients."